In [1]:
import pandas as pd
import numpy as np

In [2]:
x = pd.read_csv("../data/crayford-races.csv")
x["Race_distance"] = 380
x

Race_ID  Trap  Odds   BSP  Public_Estimate  Last_Run  Distance_All  \
0            0     6  2.75  4.00                1        12        456.47   
1            0     3  5.00  7.60                4         5        410.48   
2            0     5  5.00  9.40                6         9        386.45   
3            0     4  7.00  7.80                5         9        380.00   
4            0     2  5.00  5.10                2        13        385.00   
...        ...   ...   ...   ...              ...       ...           ...   
12001     2000     4  3.50  4.67                3         4        408.19   
12002     2000     2  7.00  9.36                6         8        418.62   
12003     2000     5  5.00  4.35                2         7        400.00   
12004     2000     1  4.00  3.86                1         3        436.36   
12005     2000     3  5.00  8.31                5         4        418.18   

       Finish_All  Distance_Places_All  Races_All  ...  Grade_380  Time_380  \
0            4.09               402.86         17  ...       4.00     17.84   
1            3.53               414.00         21  ...       3.29     24.18   
2            3.39               380.00         31  ...       3.71     24.06   
3            3.03               380.00         21  ...       4.43     24.14   
4            2.59               388.33         40  ...       2.71     24.05   
...           ...                  ...        ...  ...        ...       ...   
12001        3.25               383.91         52  ...       5.71     24.13   
12002        3.82               412.00         58  ...       4.86     20.81   
12003        4.05               410.00          9  ...       6.00     24.36   
12004        4.82               442.00         22  ...       5.71     24.13   
12005        5.66               422.50         22  ...       5.00     16.35   

       Early_Time_380  Stay_380  Favourite  Finished  Wide_380   Dist_By  \
0                3.63  0.500000        6.0         4  0.000000 -10.50000   
1                3.70  0.280000        6.0         1  0.140000  -4.71000   
2                3.67 -0.430000        6.0         3  0.000000  -2.86000   
3                3.65  0.280000        6.0         2  0.000000  -2.71000   
4                3.64 -0.430000        6.0         6  0.000000  -2.32000   
...               ...       ...        ...       ...       ...       ...   
12001            3.75 -2.000000        1.0         4  0.000000  -3.50000   
12002            3.73 -0.290000        1.0         3  0.000000 -12.43000   
12003            3.74 -0.750000        1.0         6  0.000000  -4.75000   
12004            3.74 -0.056749        1.0         2  0.068085  -4.48688   
12005            3.77  0.160000        1.0         5  0.170000 -21.00000   

       Winner  Race_distance  
0           0            380  
1           1            380  
2           0            380  
3           0            380  
4           0            380  
...       ...            ...  
12001       0            380  
12002       0            380  
12003       0            380  
12004       0            380  
12005       0            380  

[12006 rows x 29 columns]

In [3]:
x.describe()

Race_ID          Trap          Odds           BSP  Public_Estimate  \
count  12006.00000  12006.000000  12006.000000  12006.000000     12006.000000   
mean    1000.00000      3.500000      5.371940      7.600623         3.501916   
std      577.66293      1.707896      2.208432      4.255454         1.706236   
min        0.00000      1.000000      1.670000      1.830000         1.000000   
25%      500.00000      2.000000      4.000000      4.610000         2.000000   
50%     1000.00000      3.500000      5.000000      6.400000         4.000000   
75%     1500.00000      5.000000      6.000000      9.290000         5.000000   
max     2000.00000      6.000000     21.000000     44.000000         6.000000   

           Last_Run  Distance_All    Finish_All  Distance_Places_All  \
count  12006.000000  12006.000000  12006.000000         12006.000000   
mean       7.149592    400.232647      3.666011           399.435106   
std        3.346557     28.816968      0.527866            28.957759   
min        2.000000    306.670000      1.830000           307.570000   
25%        5.000000    380.000000      3.320000           380.000000   
50%        7.000000    389.520000      3.610000           388.000000   
75%        8.000000    413.995000      3.920000           412.967500   
max       28.000000    573.160000      7.270000           579.550000   

          Races_All  ...     Grade_380      Time_380  Early_Time_380  \
count  12006.000000  ...  12006.000000  12006.000000    12006.000000   
mean      62.054223  ...      5.703423     24.042455        3.703312   
std       56.200429  ...      1.797255      1.290984        0.061315   
min        2.000000  ...      1.000000      0.000000        3.500000   
25%       23.000000  ...      4.500000     24.120000        3.660000   
50%       44.000000  ...      6.000000     24.310000        3.700000   
75%       84.000000  ...      7.290000     24.510000        3.740000   
max      462.000000  ...      8.000000     25.660000        4.210000   

           Stay_380     Favourite      Finished      Wide_380       Dist_By  \
count  12006.000000  12006.000000  12006.000000  12006.000000  12006.000000   
mean      -0.058871      3.442533      3.499500      0.068360     -4.473741   
std        1.089164      1.744878      1.708042      0.152352      3.036172   
min       -5.000000      1.000000      1.000000      0.000000    -50.000000   
25%       -0.800000      2.000000      2.000000      0.000000     -5.430000   
50%        0.000000      3.000000      3.000000      0.000000     -4.000000   
75%        0.710000      5.000000      5.000000      0.068085     -2.750000   
max        5.000000      6.000000      6.000000      1.000000     11.000000   

             Winner  Race_distance  
count  12006.000000        12006.0  
mean       0.166667          380.0  
std        0.372694            0.0  
min        0.000000          380.0  
25%        0.000000          380.0  
50%        0.000000          380.0  
75%        0.000000          380.0  
max        1.000000          380.0  

[8 rows x 29 columns]

In [5]:
x["Race_ID"].nunique()

2001

In [11]:
x.columns

Index(['Race_ID', 'Trap', 'Odds', 'BSP', 'Public_Estimate', 'Last_Run',
       'Distance_All', 'Finish_All', 'Distance_Places_All', 'Races_All',
       'Distance_Recent', 'Finish_Recent', 'Odds_Recent', 'Early_Recent',
       'Races_380', 'Wins_380', 'Finish_380', 'Odds_380', 'Early_380',
       'Grade_380', 'Time_380', 'Early_Time_380', 'Stay_380', 'Favourite',
       'Finished', 'Wide_380', 'Dist_By', 'Winner', 'Race_distance'],
      dtype='object')

In [39]:
ex_race = x[x["Race_ID"] == 1]
ex_race = ex_race.sort_values("Trap")
ex_race = ex_race[["Odds", "Distance_Recent", "Finish_Recent"]].reset_index(drop=True)
print(ex_race)
ex_race["Odds"] = 1 / ex_race["Odds"]
ex_race["Distance_Recent"] = ex_race["Distance_Recent"] / 1000
ex_race["Finish_Recent"] = (6 - ex_race["Finish_Recent"]) / 5
ex_race

   Odds  Distance_Recent  Finish_Recent
0   7.0           471.43           2.29
1   5.0           380.00           3.71
2   3.5           481.43           3.57
3   4.0           380.00           2.15
4   6.0           380.00           2.29
5   5.0           425.71           5.51


Odds  Distance_Recent  Finish_Recent
0  0.142857          0.47143          0.742
1  0.200000          0.38000          0.458
2  0.285714          0.48143          0.486
3  0.250000          0.38000          0.770
4  0.166667          0.38000          0.742
5  0.200000          0.42571          0.098

In [41]:


feature

array([[0.38      ],
       [0.14285714],
       [0.47143   ],
       [0.742     ],
       [0.2       ],
       [0.38      ],
       [0.458     ],
       [0.28571429],
       [0.48143   ],
       [0.486     ],
       [0.25      ],
       [0.38      ],
       [0.77      ],
       [0.16666667],
       [0.38      ],
       [0.742     ],
       [0.2       ],
       [0.42571   ],
       [0.098     ]])

In [62]:
data = x.copy()
data["Odds"] = 1 / data["Odds"]
data["Distance_Recent"] = data["Distance_Recent"] / 1000
data["Finish_Recent"] = (6 - data["Finish_Recent"]) / 5

In [65]:
races = data["Race_ID"].unique()
features = np.empty((19, 1, len(races)))
labels = np.empty((6, 1, len(races)))

features[0, 0, :] = 380/1000
for idx, race in enumerate(races):
    dogs = data[data["Race_ID"] == race].sort_values("Trap")
    dogs = dogs[["Odds", "Distance_Recent", "Finish_Recent", "Finished"]].reset_index(drop=True)
    dogs_features = dogs.drop("Finished", axis=1).values.reshape(18, 1)
    dogs_labels = dogs["Finished"].values.reshape(6, 1)
    features[1:, 0, idx] = dogs_features[:, 0]
    labels[:, 0, idx] = dogs_labels[:, 0]


In [66]:
features

array([[[0.38      , 0.38      , 0.38      , ..., 0.38      ,
         0.38      , 0.38      ]],

       [[0.16666667, 0.14285714, 0.2       , ..., 0.18181818,
         0.25      , 0.25      ]],

       [[0.38      , 0.47143   , 0.38      , ..., 0.41714   ,
         0.42571   , 0.45714   ]],

       ...,

       [[0.36363636, 0.2       , 0.28571429, ..., 0.33333333,
         0.11111111, 0.2       ]],

       [[0.49429   , 0.42571   , 0.38      , ..., 0.38      ,
         0.38      , 0.38      ]],

       [[0.524     , 0.098     , 0.714     , ..., 0.486     ,
         0.458     , 0.542     ]]])

In [67]:
labels

array([[[5., 6., 6., ..., 4., 2., 2.]],

       [[6., 3., 5., ..., 3., 1., 3.]],

       [[1., 1., 4., ..., 5., 6., 5.]],

       [[2., 2., 1., ..., 6., 5., 4.]],

       [[3., 5., 2., ..., 1., 4., 6.]],

       [[4., 4., 3., ..., 2., 3., 1.]]])

In [68]:
labels.shape

(6, 1, 2001)

In [69]:
features.shape

(19, 1, 2001)

In [91]:
ar = np.argmin(labels, 0, keepdims=True)

In [97]:
labels_2 = np.zeros(labels.shape)
np.put_along_axis(labels_2, ar, 1, 0)

In [98]:
labels_2

array([[[0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 1., 0.]],

       [[1., 1., 0., ..., 0., 0., 0.]],

       [[0., 0., 1., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 1.]]])

In [99]:
labels[labels <= 3]

array([1., 2., 3., ..., 2., 3., 1.])