In [3]:
import torch
from torch.nn import Softmax
import sys
import os
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.dataset import GreyhoundDataset
from torch.utils.data.dataloader import DataLoader


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

In [3]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
proc = Softmax(dim=1)

In [5]:
proc.forward(x)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [6]:
ds = GreyhoundDataset(torch.device("cpu"))
load = DataLoader(ds, 32)

In [7]:
batch = next(load.__iter__())[0]

In [8]:
proc.forward(batch).sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000])